public With Sharing class vgtna_Constants {

    // Territory management
    public static final string PSR_TERRITORY = 'Previous_Sales_Relationships';
    public static final string AOR_TERRITORY = 'Area_of_Responsibility';
    public static final string ASSIGNED_TERRITORY = 'Assigned_Accounts';
    
    
    public static final string PSR_TERRITORY_TYPE = 'Previous_Sales_Relationship';
    public static final string AOR_TERRITORY_TYPE = 'Area_of_Responsibility';
    public static final string ASSIGNED_TERRITORY_TYPE = 'Assigned_Accounts';
    
    public static final string ASSIGNMENT_PARAM = 'Assignment';
    public static final string AOR_PARAM = 'AOR';
    public static final string PSR_PARAM = 'PSR';
  
    // Account RecordTypes
    public static final string ACCOUNT_DEALER_RECORDTYPE = 'Dealer';
    public static final string ACCOUNT_CUSTOMER_RECORDTYPE = 'Customer';
    
    // Opportunity RecordTypes
    public static final string MACK_OPPTY_RECORDTYPE = 'Mack';
    public static final string VOLVO_OPPTY_RECORDTYPE = 'Volvo';
    
    // brand
    public static final string MACK_BRAND = 'Mack';
    public static final string VOLVO_BRAND = 'Volvo';
    
    // Roles
    public static final string MACK_DSM_ROLE = 'US_Central_Mack_District_Sales_Manager'; 
    public static final string SYSTEM_PARTNER_ROLE = 'System_Partner_Role'; 
    public static final string VOLVO_RFM_ROLE = 'US_Central_Volvo_Regional_Fleet_Manager'; 
    public static final string MACK_RFM_ROLE = 'US_Central_Mack_Regional_Fleet_Manager'; 
    
    
    
	// Profiles
    public static final string INTEGRATION_USER_PROFILE = 'System Integrator';
    public static final string INTERNAL_USER_PROFILE = 'Volvo Sales Rep';
    public static final string MACK_INTERNAL_USER_PROFILE = 'Mack Sales Rep';
    
    public static final string DEALER_USER_PROFILE = 'Dealer User';
    
    
    // Contact Sources
    public static final string CORPORATE_CONTACT_SOURCE = 'Corporate_User';
    public static final string DEALER_CONTACT_SOURCE = 'Dealer'; 
    public static final string FLEETSEEK_CONTACT_SOURCE = 'FleetSeek'; 
    public static final string D_B_CONTACT_SOURCE = 'D&B'; 
    
    // AccountContactRelation Roles
    public static final string MACK_USER = 'Mack Sales Rep';
    public static final string MACK_MANAGER = 'Mack Sales Manager';
    public static final string VOLVO_USER = 'Volvo Sales Rep';
    public static final string VOLVO_MANAGER = 'Volvo Sales Manager';
    
}